"""Initial schema

Revision ID: 409a7d6da51e
Revises:
Create Date: 2026-09-02 23:15:31.499193

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '409a7d6da51e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('account_uuid', sa.String(
                        length=36), nullable=False),
                    sa.Column('status', sa.SmallInteger(),
                              nullable=False, comment='1=正常 2=锁定 3=已注销'),
                    sa.Column('login_policy', sa.String(
                        length=16), nullable=False),
                    sa.Column('last_login_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('account_uuid')
                    )
    op.create_table('audit_log',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('account_id', sa.BigInteger(), nullable=True),
                    sa.Column('action', sa.String(length=64), nullable=False),
                    sa.Column('target_type', sa.String(
                        length=32), nullable=True),
                    sa.Column('target_id', sa.String(
                        length=64), nullable=True),
                    sa.Column('ip', sa.String(length=45), nullable=True),
                    sa.Column('user_agent', sa.String(
                        length=512), nullable=True),
                    sa.Column('detail', mysql.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('login_log',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('account_id', sa.BigInteger(), nullable=True),
                    sa.Column('identity_type', sa.String(
                        length=20), nullable=True),
                    sa.Column('identifier', sa.String(length=255),
                              nullable=True, comment='必须脱敏后写入'),
                    sa.Column('login_ip', sa.String(
                        length=45), nullable=False),
                    sa.Column('user_agent', sa.String(
                        length=512), nullable=True),
                    sa.Column('device_id', sa.String(
                        length=128), nullable=True),
                    sa.Column('session_id', sa.String(
                        length=36), nullable=True),
                    sa.Column('status', sa.SmallInteger(),
                              nullable=False, comment='1=成功 2=失败'),
                    sa.Column('fail_reason', sa.String(
                        length=64), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('menu',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('parent_id', sa.BigInteger(), nullable=True),
                    sa.Column('menu_code', sa.String(
                        length=64), nullable=False),
                    sa.Column('menu_name', sa.String(
                        length=64), nullable=False),
                    sa.Column('menu_type', sa.SmallInteger(),
                              nullable=False, comment='1=目录 2=菜单 3=按钮'),
                    sa.Column('route_path', sa.String(
                        length=255), nullable=True),
                    sa.Column('icon', sa.String(length=64), nullable=True),
                    sa.Column('sort_order', sa.Integer(), nullable=False),
                    sa.Column('status', sa.SmallInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['parent_id'], ['menu.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('menu_code')
                    )
    op.create_table('permission',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('perm_code', sa.String(length=128),
                              nullable=False, comment='如 account:read'),
                    sa.Column('perm_name', sa.String(
                        length=64), nullable=False),
                    sa.Column('resource', sa.String(length=64), nullable=True),
                    sa.Column('api_method', sa.String(
                        length=10), nullable=True),
                    sa.Column('api_path', sa.String(
                        length=255), nullable=True),
                    sa.Column('status', sa.SmallInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('perm_code')
                    )
    op.create_table('role',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('role_code', sa.String(
                        length=64), nullable=False),
                    sa.Column('role_name', sa.String(
                        length=64), nullable=False),
                    sa.Column('description', sa.String(
                        length=255), nullable=True),
                    sa.Column('is_builtin', sa.SmallInteger(), nullable=False),
                    sa.Column('status', sa.SmallInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('role_code')
                    )
    op.create_table('account_role',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('account_id', sa.BigInteger(), nullable=False),
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.Column('granted_by', sa.BigInteger(), nullable=True),
                    sa.Column('granted_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['account.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['granted_by'], ['account.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(
                        ['role_id'], ['role.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('agent_threads',
                    sa.Column('thread_id', sa.String(
                        length=64), nullable=False, comment='与 LangGraph thread_id 一致(uuid4)'),
                    sa.Column('account_id', sa.BigInteger(),
                              nullable=False, comment='所属账号ID'),
                    sa.Column('title', sa.String(length=255),
                              nullable=False, comment='首条用户消息截断或手动重命名'),
                    sa.Column('last_message', sa.Text(),
                              nullable=True, comment='最新助手回复预览'),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['account.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('thread_id')
                    )
    op.create_table('auth_credential',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('account_id', sa.BigInteger(), nullable=False),
                    sa.Column('identity_type', sa.String(length=20),
                              nullable=False, comment='phone/email/username/wechat/...'),
                    sa.Column('identifier', sa.String(length=255), nullable=False,
                              comment='归一化标识; OAuth 为 provider:openid'),
                    sa.Column('credential_hash', sa.String(length=255),
                              nullable=True, comment='Argon2id 哈希; OAuth 为 NULL'),
                    sa.Column('oauth_provider', sa.String(
                        length=32), nullable=True),
                    sa.Column('oauth_openid', sa.String(
                        length=128), nullable=True),
                    sa.Column('oauth_unionid', sa.String(
                        length=128), nullable=True),
                    sa.Column('verified', sa.SmallInteger(), nullable=False),
                    sa.Column('status', sa.SmallInteger(),
                              nullable=False, comment='1=启用 2=禁用'),
                    sa.Column('last_used_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['account.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('role_menu',
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.Column('menu_id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['menu_id'], ['menu.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['role_id'], ['role.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('role_id', 'menu_id')
                    )
    op.create_table('role_permission',
                    sa.Column('role_id', sa.BigInteger(), nullable=False),
                    sa.Column('permission_id',
                              sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['permission_id'], ['permission.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['role_id'], ['role.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('role_id', 'permission_id')
                    )
    op.create_table('user_profile',
                    sa.Column('id', sa.BigInteger(),
                              autoincrement=True, nullable=False),
                    sa.Column('account_id', sa.BigInteger(), nullable=False),
                    sa.Column('nickname', sa.String(length=64), nullable=True),
                    sa.Column('avatar_url', sa.String(
                        length=512), nullable=True),
                    sa.Column('phone_enc', sa.VARBINARY(
                        length=512), nullable=True),
                    sa.Column('phone_hash', sa.String(
                        length=64), nullable=True),
                    sa.Column('phone_masked', sa.String(
                        length=32), nullable=True),
                    sa.Column('email_enc', sa.VARBINARY(
                        length=512), nullable=True),
                    sa.Column('email_hash', sa.String(
                        length=64), nullable=True),
                    sa.Column('email_masked', sa.String(
                        length=128), nullable=True),
                    sa.Column('id_card_enc', sa.VARBINARY(
                        length=512), nullable=True),
                    sa.Column('id_card_masked', sa.String(
                        length=32), nullable=True),
                    sa.Column('key_id', sa.String(length=32),
                              nullable=False, comment='加密密钥版本, 支持轮转'),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['account.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('account_id'),
                    sa.UniqueConstraint('email_hash'),
                    sa.UniqueConstraint('phone_hash')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    op.drop_table('role_permission')
    op.drop_table('role_menu')
    op.drop_table('auth_credential')
    op.drop_table('agent_threads')
    op.drop_table('account_role')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('menu')
    op.drop_table('login_log')
    op.drop_table('audit_log')
    op.drop_table('account')
    # ### end Alembic commands ###
